openapi: 3.0.3
info:
  title: PHOS App Store API
  version: 0.1.0
paths:
  /healthz:
    get:
      responses:
        '200': { description: OK }
  /api/info:
    get:
      responses:
        '200': { description: OK }
  /api/store/apps:
    get:
      summary: List apps
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/StoreApp' }
  /api/store/apps/{appId}/install:
    post:
      parameters:
        - in: path
          name: appId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/InstallRequest' }
      responses:
        '201': { description: Created }
  /api/store/installs:
    get:
      parameters:
        - in: query
          name: userId
          schema: { type: string }
      responses:
        '200': { description: OK }
  /api/store/installs/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
components:
  schemas:
    StoreApp:
      type: object
      properties: { id: {type: string}, name: {type: string}, description: {type: string} }
      required: [id, name]
    InstallRequest:
      type: object
      properties: { userId: { type: string } }
      required: [userId]
    Install:
      type: object
      properties:
        id: { type: string }
        userId: { type: string }
        appId: { type: string }
        installedAt: { type: string, format: date-time }
      required: [id, userId, appId, installedAt]