openapi: 3.0.3
info:
  title: PHOS Billing API
  version: 0.1.0
paths:
  /checkout/sessions:
    post:
      summary: Create checkout session
      responses:
        '201':
          description: Created
  /webhooks/stripe:
    post:
      summary: Stripe webhook receiver
      responses:
        '200':
          description: OK
components:
  schemas: {}
